<!-- JAVASCRIPTS -->
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.mobilemenu.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.mobilemenu.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.magnific-popup.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/main.js" type="text/javascript"></script>
</body>
</html>