<?= $this->doctype() ?>
<html>
<head>
    <title><?php echo $this->escape($this->pageTitle); ?></title>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/layout.css" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/admin.css" type="text/css">
</head>
<body id="top">
<div class="wrapper row2">
    <nav id="mainav" class="hoc clear">
        <ul>
            <li <?php echo $this->url() == '/' ? 'class="active"' : ''; ?>>
                <a href="<?php echo $this->baseUrl() . "/"; ?>">Visit Site</a></li>
            <li <?php echo $this->url() == '/admin/users' ? 'class="active"' : ''; ?>>
                <a href="<?php echo $this->baseUrl() . "/admin/users"; ?>">Users</a></li>
            <li <?php echo $this->url() == '/admin/reservations' ? 'class="active"' : ''; ?>>
                <a href="<?php echo $this->baseUrl() . "/admin/reservations"; ?>">Reservations</a></li>
        </ul>
        <ul class="fl_right">
            <?php
            $isLoggedIn = Zend_Auth::getInstance()->hasIdentity();
            ?>
            <?php if (!$isLoggedIn): ?>
                <li <?php echo $this->url() == '/auth/login' ? 'class="active"' : ''; ?>>
                    <a href="<?php echo $this->baseUrl() . '/auth/login'; ?>"><i class="fa fa-sign-in" aria-hidden="true"></i>
                        Login</a></li>
                <li <?php echo $this->url() == '/auth/signup' ? 'class="active"' : ''; ?>>
                    <a href="<?php echo $this->baseUrl() . '/auth/signup'; ?>"><i class="fa fa-user-plus" aria-hidden="true"></i>
                        Sign up</a></li>
            <?php endif; ?>

            <?php if ($isLoggedIn): ?>
                <li>
                    <?php $user = Zend_Auth::getInstance()->getIdentity(); ?>
                    <a class="drop" href="javascript:void(0)"> <?php echo $user->username ?> <i class="fa fa-user"></i></a>
                    <ul>
                        <li <?php echo $this->url() == '/admin' ? 'class="active"' : ''; ?>>
                            <a href="<?php echo $this->baseUrl() . '/admin'; ?>"><i class="fa fa-cogs" aria-hidden="true"></i>
                                Admin</a></li>
                        <li <?php echo $this->url() == '/auth/signup' ? 'class="active"' : ''; ?>>
                            <a href="<?php echo $this->baseUrl() . '/auth/edit'; ?>"><i class="fa fa-user" aria-hidden="true"></i>
                                Edit</a></li>
                        <li>
                            <a href="<?php echo $this->baseUrl() . '/auth/logout'; ?>"><i class="fa fa-sign-out" aria-hidden="true"></i>
                                Logout</a></li>
                    </ul>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
</div>